// AUTO-GENERATED from the live Surgical Solutions catalogue. Edit names/prices here.
export type Variant = { option: string; price: number | null; inStock: boolean };
export type Consumable = {
  type: 'simple' | 'variable';
  slug: string; name: string; image: string; description: string;
  unit: string; inStock: boolean;
  price?: number | null;
  attr?: string; variants?: Variant[]; priceMin?: number | null; priceMax?: number | null;
};
export type EnquiryProduct = { slug: string; name: string; image: string; description: string };

export const CONSUMABLES: Consumable[] = [
  { type: 'simple', slug: "10-x-10-non-woven-sterile-gauze-swabs-single-pack-of-10", name: "10 X 10 NON WOVEN STERILE GAUZE SWABS SINGLE PACK OF 10", image: "/products/R-2.jpg", unit: "X 10", inStock: true, price: 5.99, description: "Sterile non-woven gauze swabs for wound cleaning, dressing and general theatre use. Highly absorbent, low-linting and individually packed." },
  { type: 'variable', slug: "3-ply-face-masks-x50", name: "3-Ply Face Masks (x50)", image: "/products/3ply-Surgical-Mask.jpg", unit: "x50", inStock: true, attr: "Type", priceMin: 4.49, priceMax: 8.94, variants: [{ option: "Non-Medical (Blue)", price: 4.49, inStock: true }, { option: "Type II", price: 8.94, inStock: true }, { option: "Type IIR", price: 8.94, inStock: true }], description: "Comfortable 3-ply pleated face masks with a soft inner layer and adjustable nose bridge. Breathable protection for clinical and everyday environments." },
  { type: 'simple', slug: "n95-mask-with-valve", name: "3M™ Particulate Respirator, FFP2, Valved, 8822", image: "/products/N95-Face-Mask-with-Valve.jpg", unit: "each", inStock: true, price: 3.5, description: "FFP2/N95-rated particulate respirator providing a high level of filtration and a secure facial seal for protection against airborne particles." },
  { type: 'variable', slug: "barrier-standard-surgical-gown", name: "Barrier Standard Surgical Gown", image: "/products/barrier-medical-gowns.jpg", unit: "each", inStock: true, attr: "Size", priceMin: 195.0, priceMax: 310.0, variants: [{ option: "Large (x20)", price: 195.0, inStock: true }, { option: "Extra Large (x36)", price: 310.0, inStock: true }], description: "Sterile reinforced surgical gown offering a dependable fluid barrier and breathable comfort throughout long procedures. Supplied sterile and ready to wear." },
  { type: 'simple', slug: "bd-micro-fine-29g-1ml-insulin-syringes-x10", name: "BD Micro-Fine+ 29G, 1ml Insulin Syringes (x10)", image: "/products/636706189507842217_need29_web.jpg", unit: "x10", inStock: true, price: 24.6, description: "Sterile single-use syringes manufactured to precise tolerances for accurate, safe dosing. Individually packed." },
  { type: 'variable', slug: "biogel-surgical-gloves-sterile-latex-powder-free", name: "Biogel Surgical Gloves – Sterile, Latex, Powder-Free", image: "/products/515Wx515H-406-6-Primary.jpg", unit: "each", inStock: true, attr: "Size", priceMin: 128.4, priceMax: 128.4, variants: [{ option: "6", price: 128.4, inStock: true }, { option: "6.5", price: 128.4, inStock: true }, { option: "7", price: 128.4, inStock: true }, { option: "7.5", price: 128.4, inStock: true }], description: "Premium sterile surgical gloves engineered for an exceptional barrier and tactile sensitivity in theatre. Powder-free and individually sized for a secure, comfortable fit." },
  { type: 'variable', slug: "blue-nitrile-disposable-gloves-medical-grade-powder-free", name: "Blue Nitrile Disposable Gloves – Medical Grade, Powder Free", image: "/products/Blue-Nitrile-Gloves.jpg", unit: "each", inStock: true, attr: "Size", priceMin: 4.99, priceMax: 4.99, variants: [{ option: "Small", price: 4.99, inStock: true }, { option: "Medium", price: 4.99, inStock: true }, { option: "Large", price: 4.99, inStock: true }], description: "Durable medical-grade nitrile examination gloves — powder-free, latex-free and puncture resistant. Ideal for clinical, dental and general procedure use." },
  { type: 'variable', slug: "blue-sterile-nitrile-gloves-pack-of-50", name: "Blue Sterile Nitrile Gloves (Pack of 50)", image: "/products/1926.jpg", unit: "Pack of 50", inStock: true, attr: "Size", priceMin: 48.59, priceMax: 48.59, variants: [{ option: "Small", price: 48.59, inStock: true }, { option: "Medium", price: 48.59, inStock: true }, { option: "Large", price: 48.59, inStock: true }], description: "Durable medical-grade nitrile examination gloves — powder-free, latex-free and puncture resistant. Ideal for clinical, dental and general procedure use." },
  { type: 'variable', slug: "clear-vinyl-gloves-powder-free-x100", name: "Clear Vinyl Gloves – Powder Free (x100)", image: "/products/OIP-6.jpg", unit: "x100", inStock: true, attr: "Size", priceMin: 4.99, priceMax: 4.99, variants: [{ option: "Small", price: 4.99, inStock: true }, { option: "Medium", price: 4.99, inStock: true }, { option: "Large", price: 4.99, inStock: true }], description: "Lightweight powder-free vinyl examination gloves for low-risk clinical tasks, food handling and general protection. Comfortable, economical and latex-free." },
  { type: 'simple', slug: "clinell-antibacterial-hand-wipes", name: "Clinell Antibacterial Hand Wipes", image: "/products/637203144822454079_small_29-clh100d-dispenser-web.jpg", unit: "each", inStock: true, price: 14.5, description: "Antibacterial cleaning wipes for fast, effective disinfection of hands, surfaces and equipment in clinical settings." },
  { type: 'simple', slug: "clinell-universal-plastic-free-biodegradable-wipes", name: "Clinell Universal Plastic-Free Biodegradable Wipes", image: "/products/bio-wipes-web2.jpg", unit: "each", inStock: true, price: 8.6, description: "Antibacterial cleaning wipes for fast, effective disinfection of hands, surfaces and equipment in clinical settings." },
  { type: 'variable', slug: "coverall-type-5-6", name: "Coverall Type 5/6", image: "/products/PPE-Coverall.jpg", unit: "each", inStock: true, attr: "Size", priceMin: 7.5, priceMax: 7.5, variants: [{ option: "Medium", price: 7.5, inStock: true }, { option: "Large", price: 7.5, inStock: true }], description: "Type 5/6 protective coverall providing whole-body protection against fine particles and light liquid splash. Lightweight, breathable and disposable." },
  { type: 'simple', slug: "diamond-cardiology-stethoscope", name: "Diamond Cardiology Stethoscope", image: "/products/R-6.jpg", unit: "each", inStock: true, price: 63.0, description: "Precision-tuned stethoscope delivering clear acoustic performance for accurate auscultation. A dependable everyday diagnostic instrument." },
  { type: 'simple', slug: "disinfectant-5l", name: "Disinfectant 5 litre", image: "/products/R-4.jpg", unit: "each", inStock: true, price: 17.5, description: "Powerful surface disinfectant effective against a broad spectrum of bacteria and viruses. Keeps clinical surfaces hygienically clean." },
  { type: 'simple', slug: "disinfectant", name: "Disinfectant – 500ml (x12)", image: "/products/universal-spray-disinfectent-1.png", unit: "x12", inStock: true, price: 51.99, description: "Powerful surface disinfectant effective against a broad spectrum of bacteria and viruses. Keeps clinical surfaces hygienically clean." },
  { type: 'simple', slug: "disposable-16-blue-overshoes-x100", name: "Disposable 16″ Blue Overshoes (X100)", image: "/products/R-3.jpg", unit: "X100", inStock: true, price: 5.6, description: "Disposable waterproof overshoes that help maintain hygiene and keep clinical areas clean. Elasticated for a secure fit." },
  { type: 'simple', slug: "disposable-apron-100-16microns", name: "Disposable Aprons 16 microns – Thick Blue (x100)", image: "/products/Blue-Apron-16-Micron.jpg", unit: "x100", inStock: true, price: 5.99, description: "Waterproof disposable aprons offering everyday protection against splashes and contamination. Strong, lightweight and economical." },
  { type: 'variable', slug: "disposable-aprons-thick-white", name: "Disposable Aprons – Thick White", image: "/products/disposible-protective-apron-white.png", unit: "each", inStock: true, attr: "Pack", priceMin: 5.99, priceMax: 8.99, variants: [{ option: "Flat-Pack (x100)", price: 5.99, inStock: true }, { option: "Flat-Pack (x200)", price: 8.99, inStock: true }, { option: "Roll (x200)", price: 7.99, inStock: true }], description: "Waterproof disposable aprons offering everyday protection against splashes and contamination. Strong, lightweight and economical." },
  { type: 'simple', slug: "disposable-sleeve-blue", name: "Disposable Sleeves (Blue) (x 100)", image: "/products/Sleeve.jpg", unit: "x 100", inStock: true, price: 4.35, description: "Disposable protective oversleeves that guard clothing against splashes and contamination. Elasticated cuffs for a secure, comfortable fit." },
  { type: 'simple', slug: "disposable-surgical-gown-40-gsm-1", name: "Dry Procedure Gown, 40 gsm (x10)", image: "/products/Blue-40-GSM-Gown.jpg", unit: "x10", inStock: true, price: 15.0, description: "Sterile reinforced surgical gown offering a dependable fluid barrier and breathable comfort throughout long procedures. Supplied sterile and ready to wear." },
  { type: 'variable', slug: "eclipse-sterile-theatre-gowns-x28", name: "Eclipse Sterile Theatre Gowns (x28)", image: "/products/Disposable-Medical-Surgical-Gowns.jpg", unit: "x28", inStock: true, attr: "Size", priceMin: 170.0, priceMax: 265.05, variants: [{ option: "Small / Medium", price: 170.0, inStock: true }, { option: "Large", price: 265.05, inStock: true }], description: "Sterile reinforced surgical gown offering a dependable fluid barrier and breathable comfort throughout long procedures. Supplied sterile and ready to wear." },
  { type: 'variable', slug: "electrolase-single-use-electrodes-for-hyfrecator-2000", name: "Electrolase® Single-Use Electrodes for Hyfrecator® 2000", image: "/products/7-100-12.jpg", unit: "each", inStock: true, attr: "Type", priceMin: 110.55, priceMax: 110.55, variants: [{ option: "Blunt", price: 110.55, inStock: true }, { option: "Sharp", price: 110.55, inStock: true }], description: "Sterile single-use accessory for the Hyfrecator® 2000 electrosurgical unit. Consistent performance and patient safety, every procedure." },
  { type: 'simple', slug: "ethilon-suture-26mm-45cm-3-0-usp-x-12", name: "Ethilon Suture – 26mm 45cm – 3.0 USP x 12", image: "/products/W320BGbox.jpg", unit: "x 12", inStock: true, price: 34.2, description: "Sterile suture management kit with everything needed for clean, safe stitch removal. Single-use to eliminate cross-contamination." },
  { type: 'simple', slug: "gloves-box-of-100-extra-large-white", name: "Extra Large White Nitrile (Powder free) Gloves (x100)", image: "/products/White-Nitrile-Gloves.jpg", unit: "x100", inStock: true, price: 4.99, description: "Durable medical-grade nitrile examination gloves — powder-free, latex-free and puncture resistant. Ideal for clinical, dental and general procedure use." },
  { type: 'simple', slug: "face-shield-10", name: "Face Shield (x10)", image: "/products/Face-Shield-x10.jpg", unit: "x10", inStock: true, price: 10.0, description: "Protective eyewear offering a clear field of vision and reliable splash protection for clinical and laboratory settings." },
  { type: 'simple', slug: "hand-sanitiser-100ml-x24", name: "Hand Sanitiser 100ml (x24)", image: "/products/Alcohol-Hand-Sanitizer-100Ml-CLEACE-4.jpg", unit: "x24", inStock: true, price: 14.5, description: "Fast-acting hand sanitiser that kills 99.9% of germs without water. Kind to skin and ideal for clinical and on-the-go use." },
  { type: 'simple', slug: "senses-hand-sanitiser-500ml", name: "Hand Sanitiser – 500ml (x24)", image: "/products/500-ml-wholesale-hand-sanitizer__83091.jpg", unit: "x24", inStock: true, price: 108.0, description: "Fast-acting hand sanitiser that kills 99.9% of germs without water. Kind to skin and ideal for clinical and on-the-go use." },
  { type: 'simple', slug: "keller-funnel", name: "Keller Funnel", image: "/products/keller-funnel-1.jpg", unit: "each", inStock: false, price: 573.8, description: "The Keller Funnel enables a clean, no-touch delivery technique for breast implants, minimising handling and incision size." },
  { type: 'variable', slug: "large-black-nitrile-gloves", name: "Large Black Nitrile Gloves", image: "/products/black-nitrile-gloves.jpg", unit: "each", inStock: true, attr: "Pack", priceMin: 5.2, priceMax: 12.5, variants: [{ option: "x100", price: 12.5, inStock: true }, { option: "x200", price: 5.2, inStock: true }], description: "Durable medical-grade nitrile examination gloves — powder-free, latex-free and puncture resistant. Ideal for clinical, dental and general procedure use." },
  { type: 'simple', slug: "gloves-box-of-100-large-violet", name: "Large Violet Nitrile (Powder free) Gloves (x100)", image: "/products/OIP-7.jpg", unit: "x100", inStock: true, price: 4.99, description: "Durable medical-grade nitrile examination gloves — powder-free, latex-free and puncture resistant. Ideal for clinical, dental and general procedure use." },
  { type: 'simple', slug: "medline-dry-surgical-scrub-brush-pack-of-40", name: "Medline Dry Surgical Scrub Brush (Pack Of 40)", image: "/products/main_BRUSH1_PRD_3_5.jpg", unit: "Pack Of 40", inStock: true, price: 27.2, description: "Pre-operative surgical scrub brush with antiseptic sponge for thorough hand and nail preparation before theatre." },
  { type: 'simple', slug: "medline-heavy-duty-reinforced-mayo-stand-cover-box-of-54", name: "Medline Heavy Duty Reinforced Mayo Stand Cover (Box Of 54))", image: "/products/main_DYJPEMAYOM_GRPH_1_5.jpg", unit: "Box Of 54", inStock: true, price: 218.5, description: "Sterile theatre consumable manufactured to a high clinical standard for a reliable, hygienic surgical field." },
  { type: 'variable', slug: "medline-medi-loop-mini-surgical-vessel-loops-box-of-10", name: "Medline Medi-Loop Mini Surgical Vessel Loops (Box of 10)", image: "/products/main_MEDI-LoopSterileSurgicalVesselLoops_FAM_1_Transparent_1.jpg", unit: "Box of 10", inStock: true, attr: "Colour", priceMin: null, priceMax: null, variants: [{ option: "Blue", price: null, inStock: true }, { option: "Red", price: null, inStock: true }, { option: "White", price: null, inStock: true }, { option: "Yellow", price: null, inStock: true }], description: "Sterile silicone vessel loops for atraumatic retraction and identification of vessels and nerves during surgery. Colour-coded box of 10." },
  { type: 'simple', slug: "medline-non-woven-adhesive-op-tape-box-of-100", name: "Medline Non-Woven Adhesive OP-Tape (Box Of 100)", image: "/products/main_3525CEA_GRPH_1_6.jpg", unit: "Box Of 100", inStock: true, price: 171.6, description: "Sterile theatre consumable manufactured to a high clinical standard for a reliable, hygienic surgical field." },
  { type: 'variable', slug: "medline-sensicare-pi-micro-surgical-gloves", name: "Medline SensiCare® PI Micro Surgical Gloves", image: "/products/main_SeneicarePiMicro_PRD_1_6.jpg", unit: "each", inStock: true, attr: "Size", priceMin: 97.5, priceMax: 97.5, variants: [{ option: "5.5", price: 97.5, inStock: true }, { option: "6", price: 97.5, inStock: true }, { option: "6.5", price: 97.5, inStock: true }, { option: "7", price: 97.5, inStock: true }, { option: "7.5", price: 97.5, inStock: true }, { option: "8", price: 97.5, inStock: true }, { option: "8.5", price: 97.5, inStock: true }, { option: "9", price: 97.5, inStock: true }], description: "Premium sterile surgical gloves engineered for an exceptional barrier and tactile sensitivity in theatre. Powder-free and individually sized for a secure, comfortable fit." },
  { type: 'simple', slug: "medline-under-buttocks-drape-2-with-pouch-box-of-36", name: "Medline Under-Buttocks Drape 2 with Pouch (Box of 36)", image: "/products/main_8482CEA_GRPH_1_6.jpg", unit: "Box of 36", inStock: true, price: 101.25, description: "Sterile theatre consumable manufactured to a high clinical standard for a reliable, hygienic surgical field." },
  { type: 'simple', slug: "n95-ffp2-mask", name: "N95/FFP2 Mask", image: "/products/N95-Face-Mask.jpg", unit: "each", inStock: true, price: 4.5, description: "FFP2/N95-rated particulate respirator providing a high level of filtration and a secure facial seal for protection against airborne particles." },
  { type: 'simple', slug: "pro-ynr-reflex-hammer-otoscope-stethoscope-surgical-training-medical-student-kit", name: "Pro YNR Reflex Hammer Otoscope Stethoscope Surgical Training Medical Student Kit", image: "/products/151236796_1_grey_720x.jpg", unit: "each", inStock: true, price: 75.0, description: "Precision-tuned stethoscope delivering clear acoustic performance for accurate auscultation. A dependable everyday diagnostic instrument." },
  { type: 'simple', slug: "safety-glasses-x12", name: "Safety Glasses (x12)", image: "/products/Black-Rock-EN166-Safey-Specs.jpg", unit: "x12", inStock: true, price: 21.6, description: "Protective eyewear offering a clear field of vision and reliable splash protection for clinical and laboratory settings." },
  { type: 'simple', slug: "schuco-dermlite-carbon-dermatoscope", name: "Schuco DermLite Carbon Dermatoscope", image: "/products/Schuco_DermLite_Carbon_Dermatoscope.jpg", unit: "each", inStock: true, price: 1020.0, description: "High-resolution polarised dermatoscope for detailed skin-surface examination and lesion assessment. Precision optics in a portable body." },
  { type: 'simple', slug: "single-use-pencil-sheaths-for-hyfrecator-2000", name: "Single-Use Pencil Sheaths for Hyfrecator® 2000", image: "/products/OIP-1-1.jpg", unit: "each", inStock: true, price: 135.0, description: "Sterile single-use accessory for the Hyfrecator® 2000 electrosurgical unit. Consistent performance and patient safety, every procedure." },
  { type: 'simple', slug: "standard-3-layer-mask", name: "Standard 3 layer masks non-medical (Black ) – (x 50)", image: "/products/download-2.jpg", unit: "x 50", inStock: true, price: 4.49, description: "Comfortable 3-ply pleated face masks with a soft inner layer and adjustable nose bridge. Breathable protection for clinical and everyday environments." },
  { type: 'simple', slug: "sterile-dressing-packs-box-of-20", name: "Sterile Dressing Packs – Box of 20", image: "/products/OIP.jpg", unit: "Box of 20", inStock: true, price: 89.4, description: "Sterile non-woven gauze swabs for wound cleaning, dressing and general theatre use. Highly absorbent, low-linting and individually packed." },
  { type: 'simple', slug: "sterile-surgery-set-a-box-of-10", name: "Sterile Surgical Set A – Box of 10", image: "/products/143820-teqler-chirurgie-set-a-komplett-e1747394716145.jpg", unit: "Box of 10", inStock: true, price: null, description: "Manufactured to a high clinical standard and trusted by UK hospitals, surgeries and independent clinics." },
  { type: 'variable', slug: "stiefel-biopsy-punch-box-of-10", name: "Stiefel Biopsy Punch (Box of 10)", image: "/products/stiefel-punch-a-biopsie-3-mm-boite-de-10_1.jpg", unit: "Box of 10", inStock: true, attr: "Size", priceMin: 52.5, priceMax: 52.5, variants: [{ option: "2mm", price: 52.5, inStock: true }, { option: "3mm", price: 52.5, inStock: true }, { option: "4mm", price: 52.5, inStock: true }, { option: "5mm", price: 52.5, inStock: true }, { option: "6mm", price: 52.5, inStock: true }, { option: "7mm", price: 52.5, inStock: true }, { option: "8mm", price: 52.5, inStock: true }], description: "Sterile single-use dermal biopsy punch with a sharp, precision-ground cutting edge for clean, accurate tissue sampling. Supplied as a box of 10." },
  { type: 'variable', slug: "stiefel-disposable-curette-box-of-10", name: "Stiefel Disposable Curette (Box of 10)", image: "/products/OIP-5.jpg", unit: "Box of 10", inStock: true, attr: "Size", priceMin: 61.5, priceMax: 61.5, variants: [{ option: "4mm", price: 61.5, inStock: true }, { option: "7mm", price: 61.5, inStock: true }], description: "Sterile single-use dermal curette with a sharpened ring tip for precise removal of skin lesions. Disposable for guaranteed sharpness and zero cross-contamination." },
  { type: 'simple', slug: "suture-removal-kit-with-stitch-cutter-box-of-20", name: "Suture Removal Kit with Stitch Cutter- Box of 20", image: "/products/Suture-Removal-Kit-Medline.jpg", unit: "Box of 20", inStock: false, price: 100.8, description: "Sterile suture management kit with everything needed for clean, safe stitch removal. Single-use to eliminate cross-contamination." },
  { type: 'simple', slug: "swann-morton-sterile-disposable-scalpel-no-10-blade-with-polystyrene-handle-x-10", name: "Swann Morton Sterile Disposable Scalpel No.10 Blade with Polystyrene Handle x 10", image: "/products/3f274a38a1b63e744ceec46a04d9db40.jpg", unit: "x 10", inStock: true, price: 8.1, description: "Sterile single-use scalpel with a surgical stainless-steel blade and ergonomic handle. Ready to use straight from the pack — consistent, dependable and safe." },
  { type: 'simple', slug: "swann-morton-sterile-disposable-scalpel-no-15-blade-with-polystyrene-handle-x-10", name: "Swann Morton Sterile Disposable Scalpel No.15 Blade with Polystyrene Handle x 10", image: "/products/R-1.jpg", unit: "x 10", inStock: true, price: 7.75, description: "Sterile single-use scalpel with a surgical stainless-steel blade and ergonomic handle. Ready to use straight from the pack — consistent, dependable and safe." },
  { type: 'simple', slug: "syringe-dental-cartridge-metric-sterile-10-pack", name: "Syringe, Dental Cartridge Metric (Sterile) – 10 PACK", image: "/products/R.jpg", unit: "10 PACK", inStock: true, price: 70.0, description: "Sterile single-use syringes manufactured to precise tolerances for accurate, safe dosing. Individually packed." },
  { type: 'simple', slug: "tork-couch-roll-advanced-white-2-ply-150250-case-of-9-rolls-48cm-19-x-56m", name: "Tork Couch Roll Advanced White 2 Ply – 150250 – Case of 9 Rolls – 48cm/19″ x 56m", image: "/products/download.jpg", unit: "Roll", inStock: true, price: 53.99, description: "Strong, absorbent 2-ply couch roll for hygienic protection of examination couches and treatment surfaces. Case of premium rolls." },
  { type: 'variable', slug: "unisex-scrubs", name: "Unisex Scrubs", image: "/products/uniforms-unisex-scrub-set-medical-uniform-with-scrub-top-and-pants-refq8188-ropa-de-trabajo.jpg", unit: "each", inStock: true, attr: "Size", priceMin: 12.5, priceMax: 12.5, variants: [{ option: "Medium", price: 12.5, inStock: true }, { option: "Large", price: 12.5, inStock: true }], description: "Comfortable unisex medical scrubs in a hard-wearing, easy-care fabric. A clean, professional fit for theatre and clinic staff." },
  { type: 'simple', slug: "value-dual-head-stethoscope", name: "Value Dual Head Stethoscope", image: "/products/value-dual-head-stethoscope_7642.jpg", unit: "each", inStock: true, price: 7.8, description: "Precision-tuned stethoscope delivering clear acoustic performance for accurate auscultation. A dependable everyday diagnostic instrument." },
  { type: 'simple', slug: "ynr-otoscope-fiber-optic-medical-diagnostic-examination-nhs-ce-approved", name: "YNR Otoscope Fiber Optic Medical Diagnostic Examination NHS CE approved", image: "/products/image277365426_720x.jpg", unit: "each", inStock: true, price: 37.5, description: "Fibre-optic diagnostic instrument providing bright, even illumination for accurate ENT and general examination." },
];

export const PACKS: EnquiryProduct[] = [
  { slug: "eus-773a-bc-plastics-set-2", name: "EUS-780a Major Punch Biopsy Pack", image: "/products/EUS-780a_Major_Punch_Biopsy_Pack-removebg-preview.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-773a-bc-plastics-set-2-2", name: "EUS-779a Purity Bridge Breast Pack", image: "/products/EUS-779a_Purity_Bridge_Breast_Pack-removebg-preview.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-778a-bcf-dermatology-pack", name: "EUS-778a BCF Dermatology Pack", image: "/products/0001-DermatologyPack-2-scaled.jpg", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-777a-thh-excision-pack", name: "EUS-777a THH Excision Pack", image: "/products/0063-THHExcisionPackGallipot.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-774a-dr-palamaras-mohs-pack", name: "EUS-774a Dr Palamaras Mohs Pack", image: "/products/0074-DrPalamarasMohsPackGallipot-1.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-773a-bc-plastics-set", name: "EUS-773a BC Plastics Set", image: "/products/EUS-773a-BC-Plastics-Set.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-772a-ec-oculoplastic-pack", name: "EUS-772a EC Oculoplastic Pack", image: "/products/EUS-772a-EC-Oculoplastic-Pack.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-771a-bc-punch-biopsy-pack", name: "EUS-771a BC Punch Biopsy Pack", image: "/products/EUS-771a-BC-Punch-Biopsy-Pack.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-770a-chelsea-outpatient-centre-mohs-pack", name: "EUS-770a Chelsea Outpatient Centre Mohs Pack", image: "/products/0045-ChelseaOutpatientsPackGallipot-1.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-769a-fine-suture-pack-2", name: "EUS-769a Fine Suture Pack", image: "/products/0038-FineSuturePack.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-768a-punch-biopsy-pack", name: "EUS-768a Punch Biopsy Pack", image: "/products/0029-PunchBiopsyPackGallipot.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-767a-dermatology-pack", name: "EUS-767a Dermatology Pack", image: "/products/0001-DermatologyPack-scaled.jpg", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
  { slug: "eus-766a-minor-ops-pack", name: "EUS-766a Minor Ops Pack", image: "/products/0022-MinorOpsPack.png", description: "A pre-assembled sterile procedure pack, configured with the exact instruments and consumables your list needs and laid out for the way your team works. Available as a standard configuration or fully bespoke — enquire for specification and pricing." },
];

export const SINGLES: EnquiryProduct[] = [
  { slug: "sponge-holder-24cm", name: "Sponge Holder 24cm", image: "/products/24-EU-1110-Rampley-Sponge-Holder-24cm-2.jpg", description: "Precision stainless-steel sponge holding forceps for swabbing and skin preparation. Autoclavable, reusable and built to last." },
  { slug: "speculums", name: "Speculums", image: "/products/36-EU-705-Ear-Speculum-1.jpg", description: "A range of examination speculums with smooth, polished surfaces for patient comfort and a clear field of view." },
  { slug: "scissors", name: "Scissors", image: "/products/8-EU-3001001-Iris-Scissor-Straight-10cm-TC-1.jpg", description: "Surgical scissors ground for a clean, precise cut and finished in durable, corrosion-resistant stainless steel." },
  { slug: "needle-holder", name: "Needle Holder", image: "/products/EU-100-Needle-Holder-Halsey-Smooth-13cm-2.jpg", description: "Surgical needle holders with secure, finely machined jaws for confident, controlled suturing." },
  { slug: "hooks", name: "Hooks", image: "/products/46-EU-400-Gillie-Skin-Hook-16.5cm-1.jpg", description: "Surgical retraction hooks engineered for precise, atraumatic tissue handling." },
  { slug: "forceps", name: "Forceps", image: "/products/17-EU-2001001-Forcep-Adson-Toothed-12cm-TC-1.jpg", description: "A complete range of precision surgical forceps in premium stainless steel for a sure grip and lasting performance." },
  { slug: "ent", name: "ENT", image: "/products/37-EU-704-ENT-Mirror-1.jpg", description: "Precision ENT instruments crafted from premium surgical stainless steel for examination and minor procedures." },
  { slug: "curettes", name: "Curettes", image: "/products/2-EU-8001001-Volkmann-Spoon-Curette-Small-12.5cm-1.jpg", description: "Surgical curettes with sharpened tips for precise tissue removal across a range of sizes." },
  { slug: "clips", name: "Clips", image: "/products/3-EU-6001001-Backhaus-Towel-Clip-9cm-TC-1.jpg", description: "Surgical clips offering secure, dependable tissue approximation during procedures." },
  { slug: "clamps", name: "Clamps", image: "/products/31-EU-804-Hunt-Chalazion-Clamp-2.jpg", description: "Surgical clamps manufactured from premium stainless steel for reliable haemostasis and tissue control." },
  { slug: "braithwaite-humby-skin-graft-knife-tc", name: "Braithwaite Humby Skin Graft Knife TC", image: "/products/18-EU-1100001-Braithwaite-Humby-Skin-Graft-Knife-TC-1.jpg", description: "Braithwaite/Humby skin graft knife with a tungsten-carbide edge for smooth, controlled graft harvesting." },
  { slug: "barron-handles-2", name: "Barron Handles", image: "/products/4-EU-5001001-Barron-Handle-TC-1.jpg", description: "Barron handles offering a secure, comfortable grip for accurate dermal punch biopsy." },
];

export const fmtGBP = (n: number): string => '£' + n.toFixed(2);

export function priceLabel(c: Consumable): string {
  if (c.type === 'simple') return c.price == null ? 'Enquire' : fmtGBP(c.price);
  if (c.priceMin == null) return 'Enquire';
  return c.priceMin === c.priceMax ? fmtGBP(c.priceMin) : `${fmtGBP(c.priceMin)} – ${fmtGBP(c.priceMax!)}`;
}
